#!/bin/bash

YEAR=2005
STM=06
STD=28
EDM=07
EDD=26

now=`date +"%Y%m%d" -d "${STM}/${STD}/${YEAR}"`
end=`date +"%Y%m%d" -d "${EDM}/${EDD}/${YEAR}"`

DATES=()

until [ $now -eq `date +"%Y%m%d" -d "$end + 1 day"` ];
do
	DATES=("${DATES[@]}" $now)
	now=`date +"%Y%m%d" -d "$now + 1 day"`
done

for DATE in "${DATES[@]}";
do
	echo "${DATE}"
done
