#!/bin/bash

## Script: Set_KCELL
##
## Author: James McCann (mccannjb (at) gmail (dot) com)
##
## Accompanies: kcellmod, kcellPrep
##
## This script will execute the kcellmod program with the appropriate
## input files and format. This script should be modified to handle
## the desired number of input files or should be run for each batch
## of outputs from kcellPrep.
##
##

export OMP_NUM_THREADS=4

## kcellmod program location
EXECL=/nas02/home/m/c/mccannjb/Utils/kcellmod/kcellmod.linux
#EXECL=echo

## Day of Interest (DOI) (eg. 212,214,216) and the number of hours of emissions leading up (eg. 12,24,36)
## for DDM sensitivity calculations.
EPISODE=PITTSB_12HR2
DOI=216
HRBEFORE=12

days=`echo "${HRBEFORE}/24" | bc`
if [ $((${HRBEFORE} % 24)) -eq 0 ]
then
startday=`echo "${DOI}-(${days})" | bc`
else
startday=`echo "${DOI}-(${days}+1)" | bc`
fi

starthr=`echo "((0+5)-${HRBEFORE})+(24*(${DOI}-${startday}))" | bc`

echo $startday
echo $starthr

## Original point source directory and file
PTDIR=$HOME/netscr/EPA/12EUS1_F/ptsrce

## Directory for DDM files
DDMDIR=$HOME/netscr/EPA/12EUS1_F/ddm
#DDMDIR=$PTDIR

## kcellPrep result directory
KCDIR=$HOME/Utils/kcellmod/PITTSB_8x10

cd ${PTDIR}

if [ ! -d "${DDMDIR}/${EPISODE}" ]; then
	mkdir ${DDMDIR}/${EPISODE}
fi

i=1

## Implement for loop for number of kcellPrep output files
for camx in *.camx
do
for file in `ls $KCDIR/*.out`
do
# Parse the number from kcellPrep output file (WARNING: file names must contain only ONE number!)
num=`echo ${file##*/} | sed -e 's/[^0-9]//g'`
num=$(printf "%02d" $num)

if [ ! -d "${DDMDIR}/${EPISODE}" ]; then
	mkdir ${DDMDIR}/${EPISODE}
fi
if [ ! -d "${DDMDIR}/${EPISODE}/GRP${num}" ]; then
	mkdir ${DDMDIR}/${EPISODE}/GRP${num}
fi
# Execute kcellmod for the specified inputs
$EXECL << ieof
CAMx source file   |${PTDIR}/${camx}
New CAMx output    |${DDMDIR}/${EPISODE}/GRP${num}/${camx}
kcell input file   |${file}
emiss red. factor  |1.00
DDM Emiss start day|05${startday}
DDM Emiss start hr |${starthr}
ieof
#echo "CAMx source file   |${PTDIR}/${camx}"
#echo "New CAMx output    |${DDMDIR}/${EPISODE}/GRP${num}/${camx}"
#echo "kcell input file   |${file}"
#echo "emiss red. factor  |1.00"
#echo "DDM Emiss start day|05${startday}"
#echo "DDM Emiss start hr |${starthr}"
mv kcell.diag ${DDMDIR}/${EPISODE}/GRP${num}/day-${i}.diag
i=`echo "${i}+1" | bc`
done
done

echo "Completed kcell modifications"

