#!/bin/bash

## Script: Set_KCELL
##
## Author: James McCann (mccannjb (at) gmail (dot) com)
##
## Accompanies: kcellmod, kcellPrep
##
## This script will execute the kcellmod program with the appropriate
## input files and format. This script should be modified to handle
## the desired number of input files or should be run for each batch
## of outputs from kcellPrep.
##
##  

## kcellmod program location
EXECL=/nas02/home/m/c/mccannjb/Utils/kcellmod/kcellmod.linux

## Original point source directory and file
PTDIR=$HOME/Data
PTSRC="points-20050804"

## kcellPrep result directory
KCDIR=$HOME/Utils/kcellmod/Test

## Implement for loop for number of kcellPrep output files
for file in `ls $KCDIR/*.out`
do
# Parse the number from kcellPrep output file (WARNING: file names must contain only ONE number!)
num=`echo ${file##*/} | sed -e 's/[^0-9]//g'`
# Execute kcellmod for the specified inputs
$EXECL << ieof
CAMx source file   |${PTDIR}/${PTSRC}.camx
New CAMx output    |${KCDIR}/${PTSRC}.kcell.${num}.camx
kcell input file   |${file}
ieof
done

echo "Completed kcell modifications"
