#!/bin/bash

## Script: Set_KCELL
##
## Author: James McCann (mccannjb (at) gmail (dot) com)
##
## Accompanies: kcellmod
##
## This script will modify KCELL values from their present value by one.
## This is for debugging purposes.
##

## kcellmod program location
EXECL=/nas02/home/m/c/mccannjb/Utils/kcellmod/kcellmod.linux

ORIG=$1

mv ${ORIG} ${ORIG}.temp
# Execute kcellmod for the specified inputs
$EXECL << ieof
CAMx source file   |${ORIG}.temp
New CAMx output    |${ORIG}
ieof

echo "Completed kcell modifications"
